[build]
  command = "hugo $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.124.1"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.branch-deploy]
  command = "hugo $DEPLOY_PRIME_URL"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = false
